# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'detect-nf-test-changes'
description: 'Identify changed files within Nextflow repo between two branches and return them as output.'
branding:
  icon: "play"
  color: "purple"
inputs:
  root:
    description: 'Root directory of the Nextflow repository.'
    required: false
    default: '.'
  head:  
    description: 'Head reference branch (Source branch for a PR).'
    required: true
  base:
    description: 'Base reference branch (Target branch for a PR).'
    required: true
  ignored:
    description: 'List of files or file substrings to ignore. Default: [".git/*", ".gitpod.yml", ".prettierignore", ".prettierrc.yml", "*.md", "*.png", "modules.json", "pyproject.toml", "tower.yml"]'
    required: false
  include:
    description: 'Path to an include file containing a YAML of key value pairs to include in changed files. I.e., return the current directory if an important file is changed.'
    required: false
  log_level:
    description: 'Log level for the action. Default: "info".'
    required: false
  types:
    description: 'List of Nextflow component types to include in the output. Default: ["function", "process", "workflow", "pipeline"].'
    required: false
  returntype:
    description: 'Return either the nf-test file or modules/subworkflow directory of the changed files. Default: "file".'
    required: false
outputs:
  components:
    description: 'List of Nextflow components that require testing based on the branch differences.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ROOT: ${{ inputs.root }}
    HEAD: ${{ inputs.head }}
    BASE: ${{ inputs.base }}
    IGNORED: ${{ inputs.ignored }}
    INCLUDE: ${{ inputs.include }}
    LOG_LEVEL: ${{ inputs.log_level }}
    TYPES: ${{ inputs.types }}
    RETURN_TYPE: ${{ inputs.returntype }}
