name: test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: extract test tar
        run: |
          mkdir testrepo \
          && tar -xzvf .github/workflows/test.tar.gz -C testrepo --no-same-owner

      - name: default
        id: detect_module_a_default
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          log_level: DEBUG

      - name: Ignore changes in module A
        id: ignore_module_a
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          ignored: "modules/a/*"
          log_level: DEBUG

      - name: Do not return workflows
        id: do_not_return_workflows
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          types: "function,process,pipeline"
          log_level: DEBUG

      - name: Return directory
        id: detect_module_a_directory
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          n_parents: 2
          log_level: DEBUG

      - name: Detect config changes
        id: detect_config_changes
        uses: ./
        with:
          root: testrepo/test
          head: modify_nextflow_config_in_module_c
          base: main
          log_level: DEBUG

      - name: Detect additional include statement file
        id: detect_additional_include_file
        uses: ./
        with:
          root: testrepo/test
          head: modify_main_nextflow_file
          base: main
          log_level: DEBUG

      - name: Include tags
        id: detect_tags
        uses: ./
        with:
          root: testrepo/test
          head: modify_main_nextflow_file
          base: main
          tags: "PIPELINE" # should pick one test
          log_level: DEBUG

      - name: Exclude tags
        id: check_exclude_tags
        uses: ./
        with:
          root: testrepo/test
          head: modify_main_nextflow_file
          base: main
          tags: "PIPELINE" # should pick one test
          exclude_tags: "PIPELINE" # should drop the test
          log_level: DEBUG

      - name: Detect multi-line include
        id: multi_line_include
        uses: ./
        with:
          root: testrepo/test
          head: multi_line_include
          base: main
          log_level: DEBUG

      - name: print outputs
        run: |
          echo Default: ${{ steps.detect_module_a_default.outputs.components }}
          echo Ignore module A: ${{ steps.ignore_module_a.outputs.components }}
          echo No workflows: ${{ steps.do_not_return_workflows.outputs.components }}
          echo Directories: ${{ steps.detect_module_a_directory.outputs.components }}
          echo Config files: ${{ steps.detect_config_changes.outputs.components }}
          echo Additional include file: ${{ steps.detect_additional_include_file.outputs.components }}
          echo Tags: ${{ steps.detect_tags.outputs.components }}
          echo Exclude tags: ${{ steps.exclude_tags.outputs.components }}
          echo Multi-line include: ${{ steps.multi_line_include.outputs.components }}
