name: test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: extract test tar
        run: |
          mkdir testrepo \
          && tar -xzvf .github/workflows/test.tar.gz -C testrepo --no-same-owner

      - name: default
        id: detect_module_a_default
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main

      - name: Ignore changes in module A
        id: ignore_module_a
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          ignored: "./modules/a/*"

      - name: Do not return workflows
        id: do_not_return_workflows
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          types: "function,process,pipeline"

      - name: Return directory
        id: detect_module_a_directory
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          n_parents: 2

      - name: print outputs
        run: |
          echo Default: ${{ steps.detect_module_a_default.outputs.components }}
          echo Ignore module A: ${{ steps.ignore_module_a.outputs.components }}
          echo No workflows: ${{ steps.do_not_return_workflows.outputs.components }}
          echo Directories: ${{ steps.detect_module_a_directory.outputs.components }}
