name: test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: extract test tar
        run: |
          mkdir testrepo \
          && tar -xzvf .github/workflows/test.tar.gz -C testrepo --no-same-owner

      - name: debug
        run: |
          ls -lha testrepo/test

      - name: Default
        id: detect_module_a_default
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main

      - name: Ignore changes in module A
        id: ignore_module_a
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          ignored: "./modules/modules/a/*"

      - name: Do not return processes
        id: return_workflows_only
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          types: "function workflow pipeline"

      - name: Return directory
        id: detect_module_a_directory
        uses: ./
        with:
          root: testrepo/test
          head: change_module_a
          base: main
          n_type: 2
